import type { Exercise } from '../../../types'

export const webExercises: Exercise[] = [
  {
    id: 'html-1',
    chapterId: 'html-basics',
    title: 'Votre première balise',
    description: 'Créez un titre principal avec la balise `<h1>` contenant le texte "Bonjour le monde".',
    difficulty: 1,
    xpReward: 25,
    hints: ['Utilisez la balise h1 : <h1>texte</h1>'],
    hintCost: 5,
    starterCode: { html: '<!-- Écrivez votre code ici -->\n', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'h1', checks: [{ property: 'textContent', contains: 'Bonjour le monde' }] },
    ],
    mode: 'preview',
    order: 1,
  },
  {
    id: 'html-2',
    chapterId: 'html-basics',
    title: 'Un paragraphe',
    description: 'Ajoutez un paragraphe `<p>` sous le titre avec une phrase de votre choix (min. 10 caractères).',
    difficulty: 1,
    xpReward: 25,
    hints: ['La balise p sert aux paragraphes : <p>Mon texte</p>'],
    hintCost: 5,
    starterCode: { html: '<h1>Mon site</h1>\n', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'p', checks: [{ property: 'textContent', matches: '.{10,}' }] },
    ],
    mode: 'preview',
    order: 2,
  },
  {
    id: 'html-3',
    chapterId: 'html-basics',
    title: 'Liste à puces',
    description: 'Créez une liste `<ul>` avec au moins 3 éléments `<li>`.',
    difficulty: 1,
    xpReward: 30,
    hints: ['ul contient des li : <ul><li>Item</li></ul>'],
    hintCost: 5,
    starterCode: { html: '<h2>Ma liste</h2>\n', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'ul li', checks: [], minCount: 3 },
    ],
    mode: 'preview',
    order: 3,
  },
  {
    id: 'html-4',
    chapterId: 'html-basics',
    title: 'Lien hypertexte',
    description: 'Ajoutez un lien `<a href="https://github.com">` avec le texte "GitHub".',
    difficulty: 2,
    xpReward: 35,
    hints: ['<a href="url">texte</a>'],
    hintCost: 5,
    starterCode: { html: '<p>Visitez </p>\n', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'a', checks: [
        { property: 'textContent', contains: 'GitHub' },
        { property: 'href', contains: 'github.com' },
      ]},
    ],
    mode: 'preview',
    order: 4,
  },
  {
    id: 'html-5',
    chapterId: 'html-forms',
    title: 'Créer un bouton',
    description: 'Créez un bouton rouge avec le texte "Clique-moi" en utilisant un `<button>`.',
    difficulty: 2,
    xpReward: 35,
    hints: ['Utilisez style="background: red; color: white;" sur le button'],
    hintCost: 5,
    starterCode: { html: '<!-- Votre bouton -->\n', css: 'button { padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; }', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'button', checks: [{ property: 'textContent', contains: 'Clique-moi' }] },
    ],
    mode: 'preview',
    order: 5,
  },
  {
    id: 'html-6',
    chapterId: 'html-forms',
    title: 'Champ de saisie',
    description: 'Créez un `<input type="text">` avec un `<label>` associé affichant "Email".',
    difficulty: 2,
    xpReward: 40,
    hints: ['<label>Email</label><input type="text" />'],
    hintCost: 5,
    starterCode: { html: '<form>\n  \n</form>\n', css: 'input { padding: 8px; border: 1px solid #ccc; border-radius: 4px; }', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'input[type="text"]', checks: [] },
      { type: 'dom-exists', selector: 'label', checks: [{ property: 'textContent', contains: 'Email' }] },
    ],
    mode: 'preview',
    order: 6,
  },
  {
    id: 'css-1',
    chapterId: 'css-intro',
    title: 'Couleur de fond',
    description: 'Donnez un fond violet (#6C5CE7) au body via CSS.',
    difficulty: 1,
    xpReward: 30,
    hints: ['body { background-color: #6C5CE7; }'],
    hintCost: 5,
    starterCode: { html: '<h1>Titre coloré</h1>\n', css: '/* Votre CSS */\n', js: '' },
    validation: [
      {
        type: 'css-source',
        checks: [{ matches: 'background(-color)?\\s*:\\s*(#6[Cc]5[Cc][Ee]7|rgb\\s*\\(\\s*108\\s*,\\s*92\\s*,\\s*231)' }],
      },
    ],
    mode: 'preview',
    order: 7,
  },
  {
    id: 'css-2',
    chapterId: 'css-intro',
    title: 'Style de texte',
    description: 'Stylez le h1 : couleur blanche, taille 2rem, centré.',
    difficulty: 2,
    xpReward: 35,
    hints: ['h1 { color: white; font-size: 2rem; text-align: center; }'],
    hintCost: 5,
    starterCode: { html: '<h1>Mon titre</h1>\n', css: 'body { background: #1A1A2E; min-height: 100vh; margin: 0; padding: 20px; }\n', js: '' },
    validation: [
      { type: 'css-property', selector: 'h1', checks: [
        { property: 'color', contains: '#ffffff' },
        { property: 'text-align', equals: 'center' },
      ]},
    ],
    mode: 'preview',
    order: 8,
  },
  {
    id: 'css-3',
    chapterId: 'css-intro',
    title: 'Carte stylée',
    description: 'Créez une div.card avec fond blanc, border-radius 12px, padding 20px et une ombre.',
    difficulty: 2,
    xpReward: 40,
    hints: ['.card { background: white; border-radius: 12px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }'],
    hintCost: 5,
    starterCode: { html: '<div class="card">\n  <h2>Ma carte</h2>\n  <p>Contenu de la carte</p>\n</div>\n', css: 'body { background: #F8F9FC; padding: 40px; font-family: sans-serif; }\n', js: '' },
    validation: [
      { type: 'dom-exists', selector: '.card', checks: [] },
      { type: 'css-property', selector: '.card', checks: [
        { property: 'border-radius', contains: '12px' },
        { property: 'padding', contains: '20px' },
      ]},
    ],
    mode: 'preview',
    order: 9,
  },
  {
    id: 'css-4',
    chapterId: 'css-layout',
    title: 'Flexbox basique',
    description: 'Utilisez flexbox pour centrer une div.box (100x100px, fond violet) au milieu de l\'écran.',
    difficulty: 3,
    xpReward: 45,
    hints: ['.container { display: flex; justify-content: center; align-items: center; min-height: 100vh; }'],
    hintCost: 5,
    starterCode: {
      html: '<div class="container">\n  <div class="box"></div>\n</div>\n',
      css: 'body { margin: 0; }\n.container { min-height: 100vh; }\n.box { width: 100px; height: 100px; background: #6C5CE7; border-radius: 8px; }\n',
      js: '',
    },
    validation: [
      { type: 'css-property', selector: '.container', checks: [{ property: 'display', equals: 'flex' }] },
    ],
    mode: 'preview',
    order: 10,
  },
  {
    id: 'css-5',
    chapterId: 'css-layout',
    title: 'Navigation horizontale',
    description: 'Créez une nav avec 3 liens alignés horizontalement avec flexbox et gap.',
    difficulty: 2,
    xpReward: 40,
    hints: ['nav { display: flex; gap: 16px; }'],
    hintCost: 5,
    starterCode: {
      html: '<nav>\n  <a href="#">Accueil</a>\n  <a href="#">Cours</a>\n  <a href="#">Profil</a>\n</nav>\n',
      css: 'nav { padding: 16px; background: #1A1A2E; }\na { color: white; text-decoration: none; }\n',
      js: '',
    },
    validation: [
      { type: 'css-property', selector: 'nav', checks: [{ property: 'display', equals: 'flex' }] },
      { type: 'dom-exists', selector: 'nav a', checks: [] },
    ],
    mode: 'preview',
    order: 11,
  },
  {
    id: 'css-6',
    chapterId: 'css-layout',
    title: 'Grille de cartes',
    description: 'Affichez 2 div.card côte à côte avec display: grid; grid-template-columns: 1fr 1fr; gap: 16px;',
    difficulty: 3,
    xpReward: 45,
    hints: ['.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }'],
    hintCost: 5,
    starterCode: {
      html: '<div class="grid">\n  <div class="card">Carte 1</div>\n  <div class="card">Carte 2</div>\n</div>\n',
      css: '.card { background: white; padding: 20px; border-radius: 8px; }\nbody { background: #F8F9FC; padding: 20px; }\n',
      js: '',
    },
    validation: [
      { type: 'css-property', selector: '.grid', checks: [{ property: 'display', equals: 'grid' }] },
    ],
    mode: 'preview',
    order: 12,
  },
  {
    id: 'js-1',
    chapterId: 'js-basics',
    title: 'Console.log',
    description: 'Utilisez console.log pour afficher "Hello JS!"',
    difficulty: 1,
    xpReward: 35,
    hints: ['console.log("Hello JS!");'],
    hintCost: 5,
    starterCode: { html: '<p>Ouvrez la console ↓</p>\n', css: '', js: '// Votre code JS\n' },
    validation: [
      { type: 'js-output', selector: undefined, checks: [{ contains: 'Hello JS!' }] },
    ],
    mode: 'console',
    order: 13,
  },
  {
    id: 'js-2',
    chapterId: 'js-basics',
    title: 'Modifier le DOM',
    description: 'Changez le texte du paragraphe #msg en "JavaScript actif!" via JS.',
    difficulty: 2,
    xpReward: 45,
    hints: ['document.getElementById("msg").textContent = "JavaScript actif!";'],
    hintCost: 5,
    starterCode: { html: '<p id="msg">En attente...</p>\n', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: '#msg', checks: [{ property: 'textContent', contains: 'JavaScript actif!' }] },
    ],
    mode: 'preview',
    order: 14,
  },
  {
    id: 'app-1',
    chapterId: 'first-app',
    title: 'Première application',
    description: 'Créez une mini-app : titre "Mon App", un bouton stylé, et un fond dégradé. Elle s\'affichera dans le simulateur de bureau !',
    difficulty: 3,
    xpReward: 100,
    hints: [
      'Utilisez un h1, un button stylé en CSS, et body { background: linear-gradient(...) }',
    ],
    hintCost: 5,
    starterCode: {
      html: '<div class="app">\n  <h1>Mon App</h1>\n  <button>Lancer</button>\n</div>\n',
      css: 'body { margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center; font-family: sans-serif; }\n.app { text-align: center; }\nbutton { padding: 12px 24px; background: #6C5CE7; color: white; border: none; border-radius: 8px; cursor: pointer; }\n',
      js: '',
    },
    validation: [
      { type: 'dom-exists', selector: 'h1', checks: [{ property: 'textContent', contains: 'Mon App' }] },
      { type: 'dom-exists', selector: 'button', checks: [] },
    ],
    mode: 'desktop',
    order: 15,
  },
]
