import type { Exercise } from '../../../types'

export const webExercises: Exercise[] = [
  {
    id: 'html-1',
    chapterId: 'html-basics',
    title: 'Titre principal',
    description: 'Affichez « Bonjour le monde » comme titre principal de votre page.',
    explanation:
      'Il fallait écrire : `<h1>Bonjour le monde</h1>`. La balise `<h1>` est le titre le plus important de la page.',
    difficulty: 1,
    xpReward: 25,
    hints: [
      'Cherchez quelle balise sert aux titres principaux en HTML.',
      'Il existe six niveaux de titres — le premier est le plus grand.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'h1', checks: [{ property: 'textContent', contains: 'Bonjour le monde' }] },
    ],
    mode: 'preview',
    order: 1,
  },
  {
    id: 'html-2',
    chapterId: 'html-basics',
    title: 'Paragraphe',
    description: 'Ajoutez un paragraphe de texte sous votre titre (minimum 10 caractères).',
    explanation:
      'Il fallait ajouter un `<p>` avec au moins 10 caractères de texte. La balise `<p>` crée un bloc de paragraphe séparé des autres.',
    difficulty: 1,
    xpReward: 25,
    hints: [
      'Les paragraphes ont une balise dédiée, une seule lettre.',
      'Pensez à une balise courte qui commence par « p ».',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'p', checks: [{ property: 'textContent', matches: '.{10,}' }] },
    ],
    mode: 'preview',
    order: 2,
  },
  {
    id: 'html-3',
    chapterId: 'html-basics',
    title: 'Liste à puces',
    description: 'Créez une liste non ordonnée contenant au moins 3 éléments.',
    explanation:
      'Il fallait un `<ul>` avec au moins 3 `<li>` à l\'intérieur. `<ul>` est le conteneur, `<li>` chaque élément de la liste.',
    difficulty: 1,
    xpReward: 30,
    hints: [
      'Une liste a besoin d\'un conteneur et d\'éléments enfants.',
      'ul = liste non ordonnée, li = élément de liste.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'html-well-formed', checks: [] },
      { type: 'dom-exists', selector: 'ul li', checks: [], minCount: 3 },
    ],
    mode: 'preview',
    order: 3,
  },
  {
    id: 'html-4',
    chapterId: 'html-basics',
    title: 'Lien hypertexte',
    description: 'Dans un élément de votre liste, ajoutez un lien vers github.com affichant « GitHub ».',
    explanation:
      'Il fallait un lien dans un `<li>` : `<a href="https://github.com">GitHub</a>`. L\'attribut `href` indique la destination, le texte entre les balises ce qui s\'affiche.',
    difficulty: 2,
    xpReward: 35,
    hints: [
      'Les liens utilisent la balise « a » avec un attribut pour l\'adresse.',
      'Vérifiez que chaque balise ouverte a sa fermeture.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'html-well-formed', checks: [] },
      { type: 'dom-exists', selector: 'ul', checks: [] },
      { type: 'dom-exists', selector: 'ul li a', checks: [
        { property: 'textContent', contains: 'GitHub' },
        { property: 'href', contains: 'github.com' },
      ]},
    ],
    mode: 'preview',
    order: 4,
  },
  {
    id: 'html-5',
    chapterId: 'html-forms',
    title: 'Bouton',
    description: 'Ajoutez un bouton affichant « Clique-moi ».',
    explanation:
      'Il fallait : `<button>Clique-moi</button>`. La balise `<button>` crée un élément cliquable.',
    difficulty: 2,
    xpReward: 35,
    hints: [
      'Il existe une balise spécifique pour les boutons.',
      'Le texte du bouton se place entre la balise ouvrante et fermante.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'button', checks: [{ property: 'textContent', contains: 'Clique-moi' }] },
    ],
    mode: 'preview',
    order: 5,
  },
  {
    id: 'html-6',
    chapterId: 'html-forms',
    title: 'Champ de saisie',
    description: 'Créez un champ de saisie texte accompagné de la mention « Email ».',
    explanation:
      'Il fallait un `<label>Email</label>` et un `<input type="text">`. Le label décrit le champ, l\'input permet de saisir du texte.',
    difficulty: 2,
    xpReward: 40,
    hints: [
      'Un champ de texte utilise une balise avec un attribut type.',
      'La mention « Email » et le champ sont deux éléments distincts.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'input[type="text"]', checks: [] },
      { type: 'dom-exists', selector: 'label', checks: [{ property: 'textContent', contains: 'Email' }] },
    ],
    mode: 'preview',
    order: 6,
  },
  {
    id: 'css-1',
    chapterId: 'css-intro',
    title: 'Couleurs CSS',
    description: 'Fond violet (#6C5CE7) pour toute la page, texte du titre en blanc.',
    explanation:
      'Il fallait dans le CSS : `body { background-color: #6C5CE7; }` et `h1 { color: white; }`. `background-color` colore le fond, `color` la couleur du texte.',
    difficulty: 1,
    xpReward: 35,
    hints: [
      'Une règle CSS cible l\'ensemble de la page.',
      'Deux propriétés distinctes : une pour le fond, une pour le texte du titre.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      {
        type: 'css-source',
        checks: [{ matches: 'background(-color)?\\s*:\\s*(#6[Cc]5[Cc][Ee]7|rgb\\s*\\(\\s*108\\s*,\\s*92\\s*,\\s*231)' }],
      },
      {
        type: 'css-source',
        checks: [{ matches: 'h1\\s*\\{[^}]*color\\s*:\\s*(white|#fff(ff)?|rgb\\s*\\(\\s*255\\s*,\\s*255\\s*,\\s*255)' }],
      },
    ],
    mode: 'preview',
    order: 7,
  },
  {
    id: 'css-2',
    chapterId: 'css-intro',
    title: 'Taille et centrage des textes',
    description: 'Le titre doit faire 2rem et être centré horizontalement.',
    explanation:
      'Il fallait sur `h1` : `font-size: 2rem;` et `text-align: center;`. `2rem` définit la taille du texte, `text-align: center` le centre horizontalement.',
    difficulty: 2,
    xpReward: 35,
    hints: [
      'Une propriété contrôle la taille des caractères.',
      'Une autre propriété gère l\'alignement horizontal du texte.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      {
        type: 'css-source',
        checks: [{ matches: 'h1\\s*\\{[^}]*font-size\\s*:\\s*2rem' }],
      },
      {
        type: 'css-source',
        checks: [{ matches: 'h1\\s*\\{[^}]*text-align\\s*:\\s*center' }],
      },
    ],
    mode: 'preview',
    order: 8,
  },
  {
    id: 'css-3',
    chapterId: 'css-intro',
    title: 'Carte stylée',
    description: 'Créez une carte : fond blanc, coins arrondis (12px), padding 20px et une ombre portée.',
    explanation:
      'Il fallait une `<div class="card">` et en CSS : `background-color: white;`, `border-radius: 12px;`, `padding: 20px;`, `box-shadow: 0px 5px 5px black;`. La classe `card` permet de cibler l\'élément avec `.card` en CSS.',
    difficulty: 2,
    xpReward: 40,
    hints: [
      'Une div avec une classe permet de la styler en CSS.',
      'Pensez aux propriétés pour les coins, l\'espacement intérieur et l\'ombre.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: '.card', checks: [] },
      { type: 'css-source', checks: [{ matches: '\\.card\\s*\\{[^}]*box-shadow\\s*:\\s*0px\\s+5px\\s+5px\\s+black' }] },
      { type: 'css-property', selector: '.card', checks: [
        { property: 'background-color', contains: '255,255,255' },
        { property: 'border-radius', contains: '12px' },
        { property: 'padding', contains: '20px' },
        { property: 'box-shadow', matches: '^(?!none$).+' },
      ]},
    ],
    mode: 'preview',
    order: 9,
  },
  {
    id: 'css-4',
    chapterId: 'css-layout',
    title: 'Carré rose',
    description: 'Créez un carré rose de 100×100 pixels.',
    explanation:
      'Il fallait `<div class="square"></div>` et en CSS : `.square { width: 100px; height: 100px; background-color: #ffc0cb; }`.',
    difficulty: 2,
    xpReward: 35,
    hints: [
      'Une div avec une classe permet de la cibler en CSS.',
      'Trois propriétés : largeur, hauteur et couleur de fond.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: '.square', checks: [] },
      { type: 'css-property', selector: '.square', checks: [
        { property: 'width', contains: '100px' },
        { property: 'height', contains: '100px' },
        { property: 'background-color', contains: '255,192,203' },
      ]},
    ],
    mode: 'preview',
    order: 10,
  },
  {
    id: 'css-5',
    chapterId: 'css-layout',
    title: 'Navigation horizontale',
    description: 'Ajoutez une balise de navigation avec au moins 3 liens. Alignez-les horizontalement avec un écart de 16px entre eux.',
    explanation:
      'Il fallait un `<nav>` avec au moins 3 `<a>`, et en CSS : `nav { display: flex; gap: 16px; }`. Flexbox aligne les liens côte à côte, `gap` ajoute l\'espace entre eux.',
    difficulty: 2,
    xpReward: 40,
    hints: [
      'HTML5 a une balise dédiée à la navigation.',
      'Le flexbox permet d\'aligner des éléments sur une ligne.',
      'Une propriété CSS gère l\'espacement entre les éléments flex.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'html-well-formed', checks: [] },
      { type: 'dom-exists', selector: 'nav', checks: [] },
      { type: 'dom-exists', selector: 'nav a', checks: [], minCount: 3 },
      { type: 'css-source', checks: [{ matches: 'nav\\s*\\{[^}]*display\\s*:\\s*flex' }] },
      { type: 'css-source', checks: [{ matches: 'nav\\s*\\{[^}]*gap\\s*:\\s*16px' }] },
      { type: 'css-property', selector: 'nav', checks: [
        { property: 'display', equals: 'flex' },
        { property: 'gap', contains: '16px' },
      ]},
    ],
    mode: 'preview',
    order: 11,
  },
  {
    id: 'css-6',
    chapterId: 'css-layout',
    title: 'Grille de cartes',
    description: 'Affichez 2 cartes côte à côte (2 colonnes égales, espacement de 16px entre elles).',
    explanation:
      'Il fallait un `<div class="grid">` avec 2 `<div class="card">`, et en CSS : `.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }`.',
    difficulty: 3,
    xpReward: 45,
    hints: [
      'Un conteneur parent entoure les 2 cartes.',
      'Le mode grid permet de créer des colonnes.',
      'Une propriété définit le nombre de colonnes, une autre l\'espacement.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: '.grid', checks: [] },
      { type: 'dom-exists', selector: '.grid .card', checks: [], minCount: 2 },
      { type: 'css-source', checks: [{ matches: '\\.grid\\s*\\{[^}]*display\\s*:\\s*grid' }] },
      { type: 'css-source', checks: [{ matches: '\\.grid\\s*\\{[^}]*grid-template-columns\\s*:\\s*1fr\\s+1fr' }] },
      { type: 'css-source', checks: [{ matches: '\\.grid\\s*\\{[^}]*gap\\s*:\\s*16px' }] },
      { type: 'css-property', selector: '.grid', checks: [
        { property: 'display', equals: 'grid' },
        { property: 'gap', contains: '16px' },
      ]},
    ],
    mode: 'preview',
    order: 12,
  },
  {
    id: 'js-1',
    chapterId: 'js-basics',
    title: 'Sortie console',
    description: 'Faites afficher « Hello JS! » dans la console.',
    explanation:
      'Il fallait écrire dans l\'onglet JS : `console.log(\'Hello JS!\');` — cela affiche le message dans la console du navigateur.',
    difficulty: 1,
    xpReward: 35,
    hints: [
      'JavaScript a une fonction pour écrire dans la console.',
      'Cherchez console.??? avec le message entre parenthèses.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'js-output', selector: undefined, checks: [{ contains: 'Hello JS!' }] },
    ],
    mode: 'console',
    order: 13,
  },
  {
    id: 'js-2',
    chapterId: 'js-basics',
    title: 'Modifier le contenu',
    description: 'Créez un paragraphe, puis affichez « JavaScript actif! » dedans via JavaScript.',
    explanation:
      'Il fallait `<p id="msg"></p>` en HTML, puis en JS : `document.getElementById(\'msg\').textContent = \'JavaScript actif!\';`',
    difficulty: 2,
    xpReward: 45,
    hints: [
      'Identifiez votre paragraphe avec un attribut unique.',
      'Une propriété permet de changer le texte affiché.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: '#msg', checks: [{ property: 'textContent', contains: 'JavaScript actif!' }] },
    ],
    mode: 'preview',
    order: 14,
  },
  {
    id: 'app-1',
    chapterId: 'first-app',
    title: 'Première application',
    description: 'Composez une mini-app avec le titre « Mon App » et un bouton. Elle s\'ouvrira dans le simulateur de bureau.',
    explanation:
      'Il fallait un `<h1>Mon App</h1>` et un `<button>`. En combinant HTML et CSS, on compose une mini-application affichée dans le simulateur de bureau.',
    difficulty: 3,
    xpReward: 100,
    hints: [
      'Un titre et un bouton suffisent pour cette étape.',
      'Vous pouvez ajouter du CSS pour styliser votre app.',
    ],
    hintCost: 5,
    starterCode: { html: '', css: '', js: '' },
    validation: [
      { type: 'dom-exists', selector: 'h1', checks: [{ property: 'textContent', contains: 'Mon App' }] },
      { type: 'dom-exists', selector: 'button', checks: [] },
    ],
    mode: 'desktop',
    order: 15,
  },
]
